# Generated by Django 4.2.1 on 2023-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_projectmodel_options_alter_stackmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackmodel',
            name='stack_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
