# Generated by Django 4.2.1 on 2023-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_stackmodel_stack_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='proj_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='work_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
