# Generated by Django 4.2.1 on 2023-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_projectmodel_proj_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='work_date',
            field=models.CharField(default='hey', max_length=100),
            preserve_default=False,
        ),
    ]
